options:
  postgres_image:
    type: string
    default: quay.io/postres:1.5 
  redmine_image:
    type: string
    default:  quay.io/sameersbn/redmine:3.1.1-3
  port:
    type: int
    default: 8000

