#!/usr/bin/env python
import pprint
from docker import Client

cli = Client(base_url='unix:///var/run/docker.sock')
apps = cli.containers(filters={'label': 'com.juju.type=application'})
databases = cli.containers(filters={'label': 'com.juju.type=application'})



def payload_register(ptype, pklass, pid):
    from subprocess import check_call
    from shlex import split
    cmd = "payload-register {} {} {}".format(ptype, pklass, pid)
    check_call(split(cmd))

for app in apps:
   payload_register('docker', 'application', app['Id'][:6])

for db in databases:
   payload_register('docker', 'database', app['Id'][:6])

# print cli.containers(filters={'label': 'com.juju.type=database'})
